## What does the input-to-hidden weight matrix actually look like?

In [1]:
import numpy as np

np.random.seed(42)

input_neurons = 3
hidden_neurons = 4

weights_input_hidden = np.random.randn(input_neurons, hidden_neurons) * np.sqrt(1 / input_neurons)

print(weights_input_hidden)
print("Shape:", weights_input_hidden.shape)

[[ 0.28677805 -0.07982693  0.37394315  0.8793217 ]
 [-0.13518851 -0.13517904  0.91175894  0.44307865]
 [-0.27105116  0.31324719 -0.26755433 -0.2688892 ]]
Shape: (3, 4)


## What does the hidden-to-output weight matrix actually look like?

In [5]:
np.random.seed(42)

hidden_neurons = 4
output_neurons = 1

weights_hidden_output = np.random.randn(hidden_neurons, output_neurons) * np.sqrt(1 / hidden_neurons)

print(weights_hidden_output)
print("Shape:", weights_hidden_output.shape)

[[ 0.24835708]
 [-0.06913215]
 [ 0.32384427]
 [ 0.76151493]]
Shape: (4, 1)


## Forward Propagation — Input Layer → Hidden Layer

In [3]:
X = np.array([[1, 2, 3]])

weights_input_hidden = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]])

bias_hidden = np.array([[0.1, 0.1, 0.1, 0.1]])

hidden_input = np.dot(X, weights_input_hidden) + bias_hidden

print("Input:")
print(X)

print("\nWeights:")
print(weights_input_hidden)

print("\nBias:")
print(bias_hidden)

print("\nHidden Input:")
print(hidden_input)

print("\nShape:", hidden_input.shape)

Input:
[[1 2 3]]

Weights:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]

Bias:
[[0.1 0.1 0.1 0.1]]

Hidden Input:
[[3.9 4.5 5.1 5.7]]

Shape: (1, 4)


## ReLU Activation — What Happens Inside the Hidden Layer?

In [4]:
hidden_input = np.array([[-3.5, -1.0, 0.0, 2.5, 7.0]])

def relu(x):
    return np.maximum(0, x)

hidden_output = relu(hidden_input)

print("Before ReLU:")
print(hidden_input)

print("\nAfter ReLU:")
print(hidden_output)

Before ReLU:
[[-3.5 -1.   0.   2.5  7. ]]

After ReLU:
[[0.  0.  0.  2.5 7. ]]


## Forward Propagation — Hidden Layer → Output Layer

In [6]:
hidden_output = np.array([[0.0, 2.0, 0.0, 3.0]])

weights_hidden_output = np.array([[0.5],[0.2],[-0.4],[0.7]])

bias_output = np.array([[0.1]])

final_input = np.dot(hidden_output, weights_hidden_output) + bias_output

print("Hidden Output:")
print(hidden_output)

print("\nWeights Hidden to Output:")
print(weights_hidden_output)

print("\nOutput Bias:")
print(bias_output)

print("\nFinal Input:")
print(final_input)

Hidden Output:
[[0. 2. 0. 3.]]

Weights Hidden to Output:
[[ 0.5]
 [ 0.2]
 [-0.4]
 [ 0.7]]

Output Bias:
[[0.1]]

Final Input:
[[2.6]]


## Sigmoid Activation — Converting Raw Output into Probability

In [7]:
final_input = np.array([[2.6]])

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

predicted_output = sigmoid(final_input)

print("Before Sigmoid:")
print(final_input)

print("\nAfter Sigmoid:")
print(predicted_output)

Before Sigmoid:
[[2.6]]

After Sigmoid:
[[0.93086158]]


## Binary Cross-Entropy Loss — How Does the Neural Network Measure Its Mistake?

In [8]:
y_true = np.array([[1.0]])
y_pred = np.array([[0.9]])

def binary_cross_entropy(y_true, y_pred):
    epsilon = 1e-8
    y_pred = np.clip(y_pred, epsilon, 1 - epsilon)
    return -np.mean(y_true * np.log(y_pred) +(1 - y_true) * np.log(1 - y_pred))

loss = binary_cross_entropy(y_true, y_pred)

print("Actual Value:", y_true)
print("Predicted Probability:", y_pred)
print("Loss:", loss)

Actual Value: [[1.]]
Predicted Probability: [[0.9]]
Loss: 0.10536051565782628


## Output Error Calculation — The First Step of Backpropagation

In [9]:
predicted_output = np.array([[0.9],[0.2],[0.6],[0.4]])

y = np.array([[1],[0],[1],[0]])

output_error = predicted_output - y

print("Predicted Output:")
print(predicted_output)

print("\nActual Output:")
print(y)

print("\nOutput Error:")
print(output_error)

Predicted Output:
[[0.9]
 [0.2]
 [0.6]
 [0.4]]

Actual Output:
[[1]
 [0]
 [1]
 [0]]

Output Error:
[[-0.1]
 [ 0.2]
 [-0.4]
 [ 0.4]]


## Calculating the Gradient of Hidden → Output Weights

In [11]:
hidden_output = np.array([[0.0, 2.0, 0.0, 3.0]])

output_error = np.array([[-0.1]])

X_normalized = np.array([[1.0, 2.0, 3.0]])

d_weights_hidden_output = np.dot(hidden_output.T,output_error) / len(X_normalized)

print("Hidden Output:")
print(hidden_output)

print("\nHidden Output Transpose:")
print(hidden_output.T)

print("\nOutput Error:")
print(output_error)

print("\nGradient of Hidden-to-Output Weights:")
print(d_weights_hidden_output)

Hidden Output:
[[0. 2. 0. 3.]]

Hidden Output Transpose:
[[0.]
 [2.]
 [0.]
 [3.]]

Output Error:
[[-0.1]]

Gradient of Hidden-to-Output Weights:
[[ 0. ]
 [-0.2]
 [ 0. ]
 [-0.3]]


## Calculating the Output Bias Gradient

In [12]:
output_error = np.array([[-0.1],[ 0.2],[-0.4],[ 0.5]])

d_bias_output = np.mean(output_error,axis=0,keepdims=True)

print("Output Errors:")
print(output_error)

print("\nOutput Bias Gradient:")
print(d_bias_output)

print("\nShape:")
print(d_bias_output.shape)

Output Errors:
[[-0.1]
 [ 0.2]
 [-0.4]
 [ 0.5]]

Output Bias Gradient:
[[0.05]]

Shape:
(1, 1)


## Backpropagation — Passing the Error from Output Layer → Hidden Layer

In [14]:
output_error = np.array([[-0.1]])

weights_hidden_output = np.array([[ 0.5],[ 0.2],[-0.4],[ 0.7]])

hidden_input = np.array([[-2.0, 2.0, -1.5, 3.0]])

def relu_derivative(x):
    return (x > 0).astype(float)

hidden_error = np.dot(output_error,weights_hidden_output.T) * relu_derivative(hidden_input)

print("Output Error:")
print(output_error)

print("\nHidden-to-Output Weights:")
print(weights_hidden_output)

print("\nTransposed Weights:")
print(weights_hidden_output.T)

print("\nHidden Input:")
print(hidden_input)

print("\nReLU Derivative:")
print(relu_derivative(hidden_input))

print("\nFinal Hidden Error:")
print(hidden_error)

Output Error:
[[-0.1]]

Hidden-to-Output Weights:
[[ 0.5]
 [ 0.2]
 [-0.4]
 [ 0.7]]

Transposed Weights:
[[ 0.5  0.2 -0.4  0.7]]

Hidden Input:
[[-2.   2.  -1.5  3. ]]

ReLU Derivative:
[[0. 1. 0. 1.]]

Final Hidden Error:
[[-0.   -0.02  0.   -0.07]]


## Calculating the Gradient of Input → Hidden Weights

In [14]:
X_normalized = np.array([[1.0, 2.0, 3.0]])

hidden_error = np.array([[0.0, -0.02, 0.0, -0.07]])

d_weights_input_hidden = np.dot(X_normalized.T,hidden_error) / len(X_normalized)

print("Input:")
print(X_normalized)

print("\nTransposed Input:")
print(X_normalized.T)

print("\nHidden Error:")
print(hidden_error)

print("\nGradient of Input-to-Hidden Weights:")
print(d_weights_input_hidden)

print("\nShape:")
print(d_weights_input_hidden.shape)

Input:
[[1. 2. 3.]]

Transposed Input:
[[1.]
 [2.]
 [3.]]

Hidden Error:
[[ 0.   -0.02  0.   -0.07]]

Gradient of Input-to-Hidden Weights:
[[ 0.   -0.02  0.   -0.07]
 [ 0.   -0.04  0.   -0.14]
 [ 0.   -0.06  0.   -0.21]]

Shape:
(3, 4)


## Calculating the Hidden-Layer Bias Gradient

In [18]:
hidden_error = np.array([
    [0.00, -0.02, 0.00, -0.07],
    [0.00,  0.04, 0.03,  0.01],
    [0.05, -0.01, 0.00, -0.03]])

d_bias_hidden = np.mean(hidden_error,axis=0,keepdims=True)

print("Hidden Error:")
print(hidden_error)

print("\nHidden Bias Gradient:")
print(d_bias_hidden)

print("\nShape:")
print(d_bias_hidden.shape)

Hidden Error:
[[ 0.   -0.02  0.   -0.07]
 [ 0.    0.04  0.03  0.01]
 [ 0.05 -0.01  0.   -0.03]]

Hidden Bias Gradient:
[[ 0.01666667  0.00333333  0.01       -0.03      ]]

Shape:
(1, 4)


## Actual Weight and Bias Updates — Where the Neural Network Actually Learns

In [15]:
learning_rate = 0.1

weights_hidden_output = np.array([[ 0.5],[ 0.2],[-0.4],[ 0.7]])

d_weights_hidden_output = np.array([[ 0.0],[-0.2],[ 0.0],[-0.3]])

bias_output = np.array([[0.1]])

d_bias_output = np.array([[-0.1]])

weights_input_hidden = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]])

d_weights_input_hidden = np.array([
    [0.0, -0.02, 0.0, -0.07],
    [0.0, -0.04, 0.0, -0.14],
    [0.0, -0.06, 0.0, -0.21]])

bias_hidden = np.array([[0.1, 0.1, 0.1, 0.1]])

d_bias_hidden = np.array([[0.0, -0.02, 0.0, -0.07]])


print("BEFORE UPDATE")
print("\nHidden-to-Output Weights:")
print(weights_hidden_output)

print("\nOutput Bias:")
print(bias_output)

print("\nInput-to-Hidden Weights:")
print(weights_input_hidden)

print("\nHidden Bias:")
print(bias_hidden)


weights_hidden_output -= learning_rate * d_weights_hidden_output
bias_output -= learning_rate * d_bias_output
weights_input_hidden -= learning_rate * d_weights_input_hidden
bias_hidden -= learning_rate * d_bias_hidden


print("\n\nAFTER UPDATE")
print("\nHidden-to-Output Weights:")
print(weights_hidden_output)

print("\nOutput Bias:")
print(bias_output)

print("\nInput-to-Hidden Weights:")
print(weights_input_hidden)

print("\nHidden Bias:")
print(bias_hidden)

BEFORE UPDATE

Hidden-to-Output Weights:
[[ 0.5]
 [ 0.2]
 [-0.4]
 [ 0.7]]

Output Bias:
[[0.1]]

Input-to-Hidden Weights:
[[0.1 0.2 0.3 0.4]
 [0.5 0.6 0.7 0.8]
 [0.9 1.  1.1 1.2]]

Hidden Bias:
[[0.1 0.1 0.1 0.1]]


AFTER UPDATE

Hidden-to-Output Weights:
[[ 0.5 ]
 [ 0.22]
 [-0.4 ]
 [ 0.73]]

Output Bias:
[[0.11]]

Input-to-Hidden Weights:
[[0.1   0.202 0.3   0.407]
 [0.5   0.604 0.7   0.814]
 [0.9   1.006 1.1   1.221]]

Hidden Bias:
[[0.1   0.102 0.1   0.107]]
